package licensing

import (
	"bytes"
	"encoding/json"
	"errors"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// -----------------------------------------------------------------------
// Fixture-backed parity test
//
// The canonical byte sequences under fixtures/tokens/*/canonical_{header,
// payload}.bin are generated by the TypeScript canonicalizer. If our Go
// output disagrees with any byte, the languages have drifted and every
// cross-language signature verification will silently fail in production.
// -----------------------------------------------------------------------

// repoRoot walks up from this test file until it finds the `fixtures/`
// directory. Running `go test` sets the working directory to the package
// directory, which is 1 level deep (licensing/), but we don't want
// to hard-code that in case the module is ever re-rooted.
func repoRoot(t *testing.T) string {
	t.Helper()
	dir, err := os.Getwd()
	if err != nil {
		t.Fatalf("getwd: %v", err)
	}
	for range 8 {
		if _, err := os.Stat(filepath.Join(dir, "fixtures", "tokens")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			break
		}
		dir = parent
	}
	t.Fatalf("could not locate repo root (with fixtures/tokens/) from %s", dir)
	return ""
}

type fixtureInputs struct {
	Header  map[string]any `json:"header"`
	Payload map[string]any `json:"payload"`
}

func loadFixture(t *testing.T, root, name string) fixtureInputs {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(root, "fixtures", "tokens", name, "inputs.json"))
	if err != nil {
		t.Fatalf("read inputs.json for %s: %v", name, err)
	}
	// Use json.Number so integers don't round-trip through float64.
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	var in fixtureInputs
	if err := dec.Decode(&in); err != nil {
		t.Fatalf("decode inputs.json for %s: %v", name, err)
	}
	return in
}

func TestCanonicalize_FixtureParity(t *testing.T) {
	root := repoRoot(t)
	tokensDir := filepath.Join(root, "fixtures", "tokens")
	entries, err := os.ReadDir(tokensDir)
	if err != nil {
		t.Fatalf("readdir fixtures/tokens: %v", err)
	}
	if len(entries) == 0 {
		t.Fatalf("no fixture directories found under %s", tokensDir)
	}

	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		t.Run(name, func(t *testing.T) {
			in := loadFixture(t, root, name)

			wantHeader, err := os.ReadFile(filepath.Join(tokensDir, name, "canonical_header.bin"))
			if err != nil {
				t.Fatalf("read canonical_header.bin: %v", err)
			}
			gotHeader, err := Canonicalize(in.Header)
			if err != nil {
				t.Fatalf("canonicalize header: %v", err)
			}
			if !bytes.Equal(gotHeader, wantHeader) {
				t.Fatalf("header bytes diverge\nwant: %q\n got: %q", wantHeader, gotHeader)
			}

			wantPayload, err := os.ReadFile(filepath.Join(tokensDir, name, "canonical_payload.bin"))
			if err != nil {
				t.Fatalf("read canonical_payload.bin: %v", err)
			}
			gotPayload, err := Canonicalize(in.Payload)
			if err != nil {
				t.Fatalf("canonicalize payload: %v", err)
			}
			if !bytes.Equal(gotPayload, wantPayload) {
				t.Fatalf("payload bytes diverge\nwant: %q\n got: %q", wantPayload, gotPayload)
			}
		})
	}
}

// -----------------------------------------------------------------------
// Rule-level tests (independent of fixtures) so a regression in one rule is
// reported directly instead of showing up as a fixture mismatch.
// -----------------------------------------------------------------------

func TestCanonicalize_RejectsNonObjectTopLevel(t *testing.T) {
	for _, v := range []any{nil, "string", int64(1), true, []any{}, 3.14} {
		_, err := Canonicalize(v)
		if err == nil {
			t.Errorf("expected error for top-level %T(%v), got none", v, v)
			continue
		}
		if !errors.Is(err, ErrCanonicalJSONInvalidTopLevel) {
			t.Errorf("expected CanonicalJSONInvalidTopLevel, got %v", err)
		}
	}
}

func TestCanonicalize_SortsKeysByUTF16(t *testing.T) {
	// 'a', 'b', 'é' (U+00E9), '漢' (U+6F22), '𝐀' (U+1D400, surrogate pair
	// [D835, DC00]).
	// UTF-16 sort order: 'a'(0061) < 'b'(0062) < 'é'(00E9) < '漢'(6F22) < '𝐀'(D835...).
	in := map[string]any{
		"b": 1,
		"a": 2,
		"é": 3,
		"漢": 4,
		"𝐀": 5,
	}
	got, err := Canonicalize(in)
	if err != nil {
		t.Fatal(err)
	}
	want := `{"a":2,"b":1,"é":3,"漢":4,"𝐀":5}`
	if string(got) != want {
		t.Fatalf("sort order wrong\nwant: %q\n got: %q", want, string(got))
	}
}

func TestCanonicalize_EscapesControlChars(t *testing.T) {
	in := map[string]any{
		"k": "\x00\x01\x07\b\t\n\f\r\x1f\"\\",
	}
	got, err := Canonicalize(in)
	if err != nil {
		t.Fatal(err)
	}
	// Note: backspace→\b, tab→\t, newline→\n, formfeed→\f, CR→\r.
	// Other C0 → \u00XX lowercase. '/' is NOT in input here; see next test.
	want := `{"k":"\u0000\u0001\u0007\b\t\n\f\r\u001f\"\\"}`
	if string(got) != want {
		t.Fatalf("escape wrong\nwant: %q\n got: %q", want, string(got))
	}
}

func TestCanonicalize_SlashIsNotEscaped(t *testing.T) {
	got, err := Canonicalize(map[string]any{"url": "https://example.com/a/b"})
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), `"https://example.com/a/b"`) {
		t.Fatalf("slash was escaped or value mangled: %q", string(got))
	}
}

func TestCanonicalize_AstralEmittedAsUTF8(t *testing.T) {
	// U+1F600 GRINNING FACE. In UTF-16: D83D DE00. Must NOT appear as
	// \uD83D\uDE00; must appear as raw UTF-8 (F0 9F 98 80).
	got, err := Canonicalize(map[string]any{"e": "😀"})
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(got, []byte{0xF0, 0x9F, 0x98, 0x80}) {
		t.Fatalf("astral codepoint not emitted as raw UTF-8: %q", got)
	}
	if bytes.Contains(got, []byte(`\u`)) {
		t.Fatalf("astral codepoint was unicode-escaped: %q", got)
	}
}

func TestCanonicalize_IntegerBoundaries(t *testing.T) {
	ok := []int64{0, 1, -1, maxSafeInteger, minSafeInteger}
	for _, n := range ok {
		if _, err := Canonicalize(map[string]any{"n": n}); err != nil {
			t.Errorf("expected %d accepted, got %v", n, err)
		}
	}
	bad := []int64{maxSafeInteger + 1, minSafeInteger - 1}
	for _, n := range bad {
		_, err := Canonicalize(map[string]any{"n": n})
		if err == nil || !errors.Is(err, ErrCanonicalJSONInvalidNumber) {
			t.Errorf("expected InvalidNumber for %d, got %v", n, err)
		}
	}
}

func TestCanonicalize_RejectsFractionalFloat(t *testing.T) {
	_, err := Canonicalize(map[string]any{"n": 1.5})
	if err == nil || !errors.Is(err, ErrCanonicalJSONInvalidNumber) {
		t.Fatalf("expected InvalidNumber, got %v", err)
	}
}

func TestCanonicalize_RejectsNaNAndInfinity(t *testing.T) {
	cases := []float64{math.NaN(), math.Inf(1), math.Inf(-1)}
	for _, f := range cases {
		_, err := Canonicalize(map[string]any{"n": f})
		if err == nil || !errors.Is(err, ErrCanonicalJSONInvalidNumber) {
			t.Errorf("expected InvalidNumber for %v, got %v", f, err)
		}
	}
}

func TestCanonicalize_RejectsNegativeZero(t *testing.T) {
	negZero := math.Copysign(0, -1)
	_, err := Canonicalize(map[string]any{"n": negZero})
	if err == nil || !errors.Is(err, ErrCanonicalJSONInvalidNumber) {
		t.Fatalf("expected InvalidNumber, got %v", err)
	}
}

func TestCanonicalize_AcceptsFloatExactSafeInteger(t *testing.T) {
	// json.Decoder without UseNumber produces float64. Given an exact safe
	// integer, we must serialize it without a decimal point.
	got, err := Canonicalize(map[string]any{"n": float64(1700000000)})
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != `{"n":1700000000}` {
		t.Fatalf("float-as-integer wrong: %q", string(got))
	}
}

func TestCanonicalize_RejectsUnsupportedTypes(t *testing.T) {
	type S struct{ X int }
	for _, v := range []any{S{1}, complex64(1), make(chan int), func() {}} {
		_, err := Canonicalize(map[string]any{"n": v})
		if err == nil || !errors.Is(err, ErrCanonicalJSONInvalidType) {
			t.Errorf("expected InvalidType for %T, got %v", v, err)
		}
	}
}

func TestCanonicalize_RejectsInvalidUTF8(t *testing.T) {
	bad := string([]byte{0xff, 0xfe}) // lone continuation bytes, not valid UTF-8
	_, err := Canonicalize(map[string]any{"k": bad})
	if err == nil || !errors.Is(err, ErrCanonicalJSONInvalidUTF8) {
		t.Fatalf("expected InvalidUTF8, got %v", err)
	}
}

func TestCanonicalize_EmptyContainers(t *testing.T) {
	got, err := Canonicalize(map[string]any{
		"a": []any{},
		"o": map[string]any{},
	})
	if err != nil {
		t.Fatal(err)
	}
	want := `{"a":[],"o":{}}`
	if string(got) != want {
		t.Fatalf("empty containers wrong\nwant: %q\n got: %q", want, string(got))
	}
}
