// Code generated by release-please + scripts/sync-versions.mjs. DO NOT EDIT.
package licensing

// Version is the licensing module release, kept in sync with the root VERSION
// file so TypeScript packages and the Go module ship matching versions.
const Version = "0.1.0-rc.0" // x-release-please-version
