/**
 * Client-side hook into nuxt-open-fetch's onResponseError.
 *
 * Two responsibilities, both of which must run exactly once per error,
 * not once per component that happens to call the API:
 *
 *   1. 401 → redirect to /sign-in (wired at 13.3). Also clears the
 *      local session cache so `useUserSession().loggedIn` flips to
 *      false immediately — otherwise nav guards misfire on the next
 *      route.
 *   2. Normalise the upstream error envelope. The licensing API emits
 *      `{ success: false, error: { code, message } }`; we surface
 *      `error.code` on the FetchError so UI code can `switch` on stable
 *      identifiers (see `@licensing/sdk` error taxonomy) instead of
 *      regexing message strings.
 *
 * Hook name comes from nuxt-open-fetch: `openFetch:onResponseError:<client>`
 * (see node_modules/nuxt-open-fetch/dist/runtime/fetch.js).
 */

type ApiErrorEnvelope = { error?: { code?: string; message?: string } };

export default defineNuxtPlugin((nuxtApp) => {
  // The module emits both a generic and a per-client hook; we subscribe
  // to the per-client one so other clients added later don't get
  // licensing's 401 behaviour. The hook name and its context type are
  // generated by nuxt-open-fetch into `.nuxt/types/open-fetch-hooks.d.ts`.
  nuxtApp.hooks.hook('openFetch:onResponseError:licensing', async (ctx) => {
    const status = ctx.response?.status;

    if (status === 401) {
      const { clear } = useUserSession();
      await clear();
      const route = useRoute();
      if (route.path !== '/sign-in') {
        await navigateTo('/sign-in', { replace: true });
      }
      return;
    }

    // Normalise the envelope so components can match on `error.message`.
    const envelope = (ctx.response as Response & { _data?: ApiErrorEnvelope })._data;
    const code = envelope?.error?.code;
    if (code && ctx.error) {
      Object.assign(ctx.error, { message: code });
    }
  });
});
